### ISSUE TITLE
Include `::1 localhost` in /etc/hosts

### ISSUE THREAD

**Issue by treysis** [ubuntu/WSL#160]
When having the hosts file generated by WSL, it parses Windows' hosts file and appends some lines of its own:

```
# This file is automatically generated by WSL based on the Windows hosts file:
# %WINDIR%\System32\drivers\etc\hosts. Modifications to this file will be overwritten.
127.0.0.1	localhost
127.0.1.1	<name of host> 

<Windows hosts file entries>

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

How can I edit those lines that are appended? More specifically, I want to include `::1 localhost` which Ubuntu for some reason decided against (although plenty other distros implement it which should be the way to go, e.g. Windows, macOS, Debian, ArchLinux, Gentoo, OpenWrt).

**Comment by didrocks** [comment]
It seems people are trying to find why and ask you questions on what you are trying to achieve: https://lists.ubuntu.com/archives/ubuntu-devel-discuss/2022-April/019237.html

I suggest you solve it here first, so that if there are some issues, this is fixed for the whole ubuntu distro and not only WSL. You can disable hosts generation from Windows and edit the file yourself, following this: https://docs.microsoft.com/en-us/windows/wsl/wsl-config

I’m thus closing the bug here as it’s not the correct place to get it changed.
