### ISSUE TITLE
Installing language packs takes a while

### ISSUE THREAD

**Issue by jibel** [ubuntu/WSL#187]
Windows 21H2 / Ubuntu 22.04

Installing the language packs in WSL takes around 4 min (tested on Azure) while the apt operation is around 30s. It seems that there are networking issues in the WSL instance and downloading takes far more time that it should.
For example, resolving the hostname ends up with a 1s timeout, 

This needs investigation.

**Comment by CarlosNihelton** [comment]
I did some comparisons with my modest internet speed to try to get a feeling of what is going on. I noticed that WSL internet speed is quite close to Windows's on my machine, but much reduced in the VM. Not the speed itself, but the reduction, might be related to such delay. The actual `apt` execution is almost 2 to 3 times longer in the VM than in my machine, even though it has a 10x faster connection, so that might be processing power. 

My laptop has the latest insiders build and WSL app from store.

My laptop / internet connection

![bare_metal_speed_test](https://user-images.githubusercontent.com/11138291/165936219-22fb66da-2377-49df-befd-d184f1fd2099.png)


A Win11 VM in Azure:
![wsldev1_speedtest](https://user-images.githubusercontent.com/11138291/165936293-5587d020-efdd-4487-9495-b64add2b2b04.png)


There are three interesting open issues on WSL repository that might also be related to this:

https://github.com/microsoft/WSL/issues/4901

https://github.com/microsoft/WSL/issues/4139

https://github.com/microsoft/WSL/issues/5256

**Comment by CarlosNihelton** [comment]
While the issue is not completely uncovered, since https://github.com/canonical/subiquity/pull/1303 we avoid extra work saving a few tens of seconds.

**Comment by CarlosNihelton** [comment]
With the latest 3 PRs this becomes no longer relevant.
