### ISSUE TITLE
[Ubuntu 22.04, GUI] Profile Setup: broken UTF-8 encoding

### ISSUE THREAD

**Issue by andremarcondesteixeira** [ubuntu/WSL#275]
### cmd /c ver

Microsoft Windows [Version 10.0.22621.521]

### wsl --status

Default Version: 2
WSL1 is not supported with your current machine configuration.
Please enable the "Windows Subsystem for Linux" optional component to use WSL1.
WSL version: 0.66.2.0
Kernel version: 5.15.57.1
WSLg version: 1.0.42
MSRDC version: 1.2.3401
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.521

### Did the problem occur during installation?

- [X] Yes

### What happened?

There is a screen asking to setup username and password:
![screenshot](https://user-images.githubusercontent.com/4294962/191787010-f5306612-3359-4e82-bf5e-2ae48c80d276.png)
When I click continue, nothing happens, and installation is left incomplete, with root user as default

### What was expected?

it should work

### Steps to reproduce

Install Ubuntu 22.04 from Microsoft Store and follow installation steps

**Comment by EduardGomezEscandell** [comment]
**Cause**
It's because of a bug in handling encoding of your full names. It happened to me, `Edu Gómez` failed whereas `Edu Gomez` worked. 

- @andremarcondesteixeira The issue is the handling of the `é` in your name.
- @Diegorro98, the issue is in the handling of the `ú` and `í` in your name and surname.

**Fix incoming**
This was fixed here https://github.com/canonical/ubuntu-desktop-installer/pull/1134 and should reach WSL soon.

**Workaround**
As a temporary workaround, you can write your names without the accent marks and it should work. If so, please report back so that we can confirm this was the problem.
