### ISSUE TITLE
how to remove '=' from git dir

### ISSUE THREAD

**Issue by eldoranstars** [ubuntu/WSL#403]
### cmd /c ver

Microsoft Windows [Version 10.0.19044.1415]

### wsl --status

5.10.102.1

### Did the problem occur during installation?

- [ ] Yes

### What happened?

![image](https://github.com/ubuntu/WSL/assets/45801218/8761e79e-2ffb-445f-9874-354feff32548)

### What was expected?

![image](https://github.com/ubuntu/WSL/assets/45801218/65826ca2-0e65-4462-8b42-53568fc22ab1)

### Steps to reproduce

`wsl --install`
```
sudo apt update && sudo apt upgrade -y
sudo apt install zsh -y
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="powerlevel10k\/powerlevel10k"/g' ~/.zshrc
```

### Additional information

i want to remove = symbol
can you help me plz?

**Comment by EduardGomezEscandell** [comment]
Hello, and thanks for your report!

Have you reproduced this issue outside of WSL? At first, it would seem like a ZSH issue rather than a WSL one. Please try checking out https://github.com/ohmyzsh/ohmyzsh/issues to see if someone else is experimenting similar issues, and consider posting there before we try to see if WSL is at fault.

Thank you.

**Comment by eldoranstars** [comment]
https://github.com/romkatv/powerlevel10k/issues/2377
