### ISSUE TITLE
Permission issue on Ubuntu-24.04 when create symlink on mnt drives

### ISSUE THREAD

**Issue by zohaibhassan156** [ubuntu/WSL#467]
### cmd /c ver

Microsoft Windows [Version 10.0.22631.3527]

### wsl --status

Default Distribution: MyWSL
Default Version: 2

### Did the problem occur during installation?

- [ ] Yes

### What happened?

I am using .bash_aliases and .gitconfig from windows via symlinks like

`ln -s /mnt/c/Users/Zohaib/.bash_aliases .bash_aliases`

In Ubuntu-24.04 when I open file with `nano .bash_aliases` it open file with message: **[   File '.bash_aliases' is unwriteable   ]**

Works fine with sudo permission.

### What was expected?

I am using same **.bash_aliases**, **.gitconfig** and **.ssh/** with on all Ubuntu-22 Distros and it never ask for sudo permission.

Today I install Ubuntu-24.04 for new project and it start asking for **sudo** permission

### Steps to reproduce

wsl -d Ubuntu-22.04
nano /mnt/c/Users/Zohaib/.bash_aliases
ln -s /mnt/c/Users/Zohaib/.bash_aliases .bash_aliases 
exit

wsl -d Ubuntu-24.04
ln -s /mnt/c/Users/Zohaib/.bash_aliases .bash_aliases 
nano .bash_aliases 

-note I am using same user: zohaib on my all Distros. 

zohaib@My-WSL:~$ cat /etc/wsl.conf

[boot]
systemd=true

[user]
default=zohaib

[network]
hostname=My-WSL

[automount]
enabled=true
options=metadata,uid=1000,gid=1000,umask=022

**Comment by zohaibhassan156** [comment]
even can't make a new file in /mnt/c/Users/Zohaib on Ubuntu-24.04
**nano /mnt/c/Users/Zohaib/.bash_aliases** leads to error: 
![image](https://github.com/ubuntu/WSL/assets/19224021/6d79a1ca-e50d-41cf-81b2-00d8ac2dde22)

**Comment by zohaibhassan156** [comment]
no. In Ubuntu-24.04 its changed. now there is a new user(ubuntu) and 1000 UID assigned to ubuntu user.

In Ubuntu-22 there was no default(ubuntu) user

**Comment by CarlosNihelton** [comment]
So, as you can realize, the permission issues you've seen is due the mismatch of your default user UID and the ones assigned via automount options `metadata,uid=1000,gid=1000,umask=022`. The fix for the existence of the default user you mention is recent and will be in the next publication to MS Store.

**Comment by MuhammadAlhomed** [comment]
I was having the same issues dealing with docker containers and npm permissions in Ubuntu 24 in WSL. I found a workaround that seems to work in my case. I will write the full process for everyone's convenience.

First, in Ubuntu terminal do  `sudo nano /etc/wsl.conf` and then add the following.
Any instance of 'YOUR-USERNAME' needs to be replaced with your username, in your case 'zohaib'.

```
[boot]
systemd=true

[user]
default=YOUR-USERNAME

[automount]
enabled=true
options=metadata,uid=1000,gid=1000,umask=022
```

Second, `sudo nano /etc/passwd`, you will see the following at the end of the file:

```
...
...
ubuntu:x:1000:1000:Ubuntu:/home/ubuntu:/bin/bash
YOUR-USERNAME:x:1002:1002:,,,:/home/YOUR-USERNAME:/bin/bash
```

Delete the ubuntu line and change yours to become the following

```
...
...
YOUR-USERNAME:x:1000:1000:,,,:/home/YOUR-USERNAME:/bin/bash
```

After that you need to change the owner of the home folder since your uid will be 1000 but your home folder will have the uid of 1002, To fix that simply do `sudo chown -R $USER /home/$USER`

This worked on a clean install, if you face some issues with permissions, you can either fix it using `sudo chown -R $USER ./FOLDER` to the offending folder or you could do a clean install of Ubuntu to not face these issues again.

**Comment by thangckt** [comment]
I have the `operation not permitted` error when using `pip install .` with a local package located in `/mnt/d`.

I try with Ubuntu 24 and 22, both of them have this problem.
But when I copy the package to `~/folder`, the error disappears.

I think that, this error relate to the writable permission.
